global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using AdventureAPI.Core.Aggregates.StoreAggregate;
global using AdventureAPI.UseCases.Stores.Create;
global using FluentAssertions;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
